sudo: required

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y openssh-client
  - chmod 700 ssh-keys
  - chmod 600 ssh-keys/*
  - docker-compose build
  - docker-compose up -d

script:
  - ssh -p 2222 -i ./ssh-keys/id_rsa.mpi -o StrictHostKeyChecking=no mpi_user@localhost -- mpirun -np 16 hostname

after_success:
  - docker-compose down

notifications:
  slack: microbrain:dHXYnMz4KBlHXHLs64ju5h5Y
