version: "2"

services:
  master:
    build: ./docker-image
    container_name: master
    ports:
      - "2222:22"
    volumes:
      - hosts:/hosts
      - ./mpi:/mpi-app
  node:
    build: ./docker-image
    command: ./compose-start.sh
    volumes_from:
      - master

networks:
  default:
    driver: bridge

volumes:
  hosts:
