version: "2"

services:
  master:
    build: .
    container_name: master
    ports:
      - "2222:22"
  node0:
    build: .
    container_name: node0
  node1:
    build: .
    container_name: node1
  node2:
    build: .
    container_name: node2
  node3:
    build: .
    container_name: node3

networks:
  default:
    driver: bridge
